#!/usr/bin/env bash

set -e

function show_usage() {
    echo ""
    echo "Usage: clean-node-modules [--delete]"
    echo ""

    exit 0
}

function find_node_modules() {
    find . -type d -name node_modules -exec echo '{}' ';'

    echo ""
    echo "Find only, use --delete to proceed"
    echo ""

    exit 0
}

function delete_node_modules() {
    find . -type d -name node_modules -exec rm -rf '{}' ';'

    echo ""
    echo "Files deleted"
    echo ""

    exit 0
}

case "$1" in
    -h) show_usage ;;
    --help) show_usage ;;

    --delete) delete_node_modules ;;

    *) find_node_modules ;;
esac

